version: '3'
services:
  dbt-bq:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - WORKSPACE_DIR=/workspaces/repo-name
      - DBT_PROFILES_DIR=${WORKSPACE_DIR}/.dbt
      - GOOGLE_APPLICATION_CREDENTIALS=${WORKSPACE_DIR}/.gcp/credentials.json
    volumes:
      - ../:${WORKSPACE_DIR}
    ports:
      - "8080:8080"